Areas/User/Controllers/ComputerController.cs
using AppModel.Models;
using AppWebMVC.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AppWebMVC.Areas.User.Controllers
{
    [Area(RolesTypes.User)]
    [Authorize(Roles = RolesTypes.User + "," + RolesTypes.Admin)]
    public class ComputerController : Controller
    {
        private readonly IComputerServices _computerServices;


        public ComputerController(IComputerServices computerServices)
        {
            _computerServices = computerServices;
        }

        public ActionResult Index()
        {
            var computers = _computerServices.GetAll();
            return View(computers);
        }
    }
}

Areas/User/Controllers/GraphicsController.cs
using AppWebMVC.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using AppModel.Models;
using Microsoft.AspNetCore.Authorization;


namespace AppWebMVC.Areas.User.Controllers
{
    [Area(RolesTypes.User)]
    [Authorize(Roles = RolesTypes.User + "," + RolesTypes.Admin)]
    public class GraphicsController : Controller
    {
        private readonly IGraphicsServices _graphicsServices;
        public GraphicsController(IGraphicsServices graphicsServices)
        {
            _graphicsServices = graphicsServices;
        }
        // GET: GraphicsController
        public ActionResult Index()
        {
            var graphics = _graphicsServices.GetAll();
            return View(graphics);
        }
    }
}

Areas/User/Controllers/ProducerController.cs
using AppModel.Models;
using AppWebMVC.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Security.Policy;

namespace AppWebMVC.Areas.User.Controllers
{
    [Area(RolesTypes.User)]
    [Authorize(Roles = RolesTypes.User + "," + RolesTypes.Admin)]
    public class ProducerController : Controller
    {
        private readonly IProducerServices _producerServices;
        public ProducerController(IProducerServices producerServices)
        {
            _producerServices = producerServices;
        }
        // GET: ProducerController
        public ActionResult Index()
        {
            var producers = _producerServices.GetAll();
            return View(producers);
        }
    }
}

Views/Shared/_Layout.cshtml
@using AppModel.Models;
@using Microsoft.AspNetCore.Identity;
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AppWebMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AppWebMVC.styles.css" asp-append-version="true" />

    <!-- Add css-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/css/select2.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/select2-bootstrap-5-theme@1.3.0/dist/select2-bootstrap-5-theme.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/select2-bootstrap-5-theme@1.3.0/dist/select2-bootstrap-5-theme.rtl.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AppWebMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if (SignInManager.IsSignedIn(User))
                        {
                            @if (User.IsInRole(RolesTypes.Admin) || User.IsInRole(RolesTypes.User))
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-expanded="false">
                                        Menu User
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                        <a class="dropdown-item" asp-area="User" asp-controller="Computer" asp-action="Index">Computer</a>
                                        <a class="dropdown-item" asp-area="User" asp-controller="Graphics" asp-action="Index">Graphics</a>
                                        <a class="dropdown-item" asp-area="User" asp-controller="Producer" asp-action="Index">Producer</a>
                                    </div>
                                </li>
                            }
                            <ul class="navbar-nav">
                                @if (User.IsInRole(RolesTypes.Admin))
                                {
                                    <li class="nav-item dropdown">
                                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-expanded="false">
                                            Menu Admin
                                        </a>
                                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                            <a class="dropdown-item" asp-area="Admin" asp-controller="Computer" asp-action="Index">Computer</a>
                                            <a class="dropdown-item" asp-area="Admin" asp-controller="Graphics" asp-action="Index">Graphics</a>
                                            <a class="dropdown-item" asp-area="Admin" asp-controller="Producer" asp-action="Index">Producer</a>
                                        </div>
                                    </li>
                                }
                            </ul>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - AppWebMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <!-- Add js -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.0/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/select2.full.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>